from .nsi_customer_registry import NsiCustomerRegistry
from .ikul import NsiRegIkul
from .okved import NsiRegOkved
from .okved_activity import NsiRegOkvedActivity
from .okved2 import NsiRegOkved2
from .okved_activity2 import NsiRegOkved2Activity
from .fz223type_as import NsiRegClassificationFz223type
from .contact import NsiRegContact
from .granted_user import NsiRegGrantedUser
from .capital_stock_agency import NsiRegCapitalStockAgency