from .customer import NsiOrgCustomer
from .nsi_organization import NsiOrganization
from .okved import NsiOrgOkved
from .okved_activity import NsiOrgOkvedActivity
from .okved2 import NsiOrgOkved2
from .okved_activity2 import NsiOrgOkved2Activity
from .fz223type import NsiOrgFz223type
from .nsi_org_fz223type_as import NsiOrgFz223typeAs
from .contact import NsiOrgContact
from .successor import NsiOrgSuccessor