from .template import NsiOrderClauseTemplate
from .template_field import NsiOrderClauseFieldTemplate

from .order_clause import NsiOrderClause
from .order_clause_template_as import NsiOrderClauseTemplateAs